### ISSUE TITLE
issue in build config file  .travis.yml

### ISSUE THREAD

**Issue by shreyanshu7101904** [Curioo/emailpyspam#15]
i have checked travis ci logs there is issue in build config and test script.

**Comment by Curioo** [comment]
ive noticed, im currently working on making a script, as im not sure how to simulate keyboard input right now.

**Comment by Curioo** [comment]
if you have a suggestion on fixing it, make a pull request.

**Comment by shreyanshu7101904** [comment]
yeah sure

**Comment by Curioo** [comment]
I have decided to remove travis CLI altogether because this project is not suitable for it. This project relies heavily on user input which is custom so there is no point telling a bot to attempt to run this program. 
Sorry for the late reply, 
Max
