### ISSUE TITLE
How do you send each email separately?

### ISSUE THREAD

**Issue by oscarrcano** [Curioo/emailpyspam#22]
When your recipients recive the email they know all the people you have sent this to, Is there a way to disable that?

**Comment by Curioo** [comment]
Hey there! Unfortunately, this is not possible due to the way we handle lists. Also, you'd be hitting the rate limit to sending emails very fast. If you insist on sending emails separately, try launching separate instances of the program. 

I'll mark this as an enhancement for now as I might work on a feature like this.

**Comment by NONAME1103** [comment]
The latest version of the master branch now has an implementation for the use of the BCC option that would prohibit recipients from viewing other recipients. 

Thank you for submitting this issue and feel free to open other issues for recommended implementations or problems in the future.

**Comment by oscarrcano** [comment]
Hey, I'm here again I have already tried it and it seems like I'm doing something bad.![Screenshot_20210216_172516.jpg](https://user-images.githubusercontent.com/78900509/108091686-3d33e980-707c-11eb-9076-8efc4007685d.jpg)

This is the email I got using the BCC option and I can see the emails.

**Comment by NONAME1103** [comment]
Sorry for the incomplete solution. I had my gmail with BCC working on Outlook previously but did not check other email viewers. There should now be a solution that works globally. 
Thank you for your patience and I hope you can try again with more success so that we may close this issue.

**Comment by Curioo** [comment]
Stale.
