### ISSUE TITLE
error in imports

### ISSUE THREAD

**Issue by divyansh343** [Curioo/emailpyspam#24]
Issue tracker is used for reporting bugs.

i got 2 errors

Traceback (most recent call last):
  File "E:\spam\emailpyspam\main\emailspam.py", line 12, in <module>
    from tabulate import tabulate
  File "C:\Python310\lib\site-packages\tabulate.py", line 16, in <module>
    from collections import Iterable
ImportError: cannot import name 'Iterable' from 'collections' (C:\Python310\lib\collections\__init__.py)
## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

i g ot

**Comment by maxsptz** [comment]
@divyansh343 what version of python are you using?

**Comment by divyansh343** [comment]
3.9

**Comment by maxsptz** [comment]
Hey, could you do `pip freeze`, or `pip3 freeze` and send the output here please?
Do this in the directory of the project.
